apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: private-quarkus-devfile-sample-ur4m
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: private-quarkus-devfile-sample-ur4m
    app.kubernetes.io/part-of: private-devfile
  name: private-quarkus-devfile-sample-ur4m
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: private-quarkus-devfile-sample-ur4m
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: private-quarkus-devfile-sample-ur4m
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-izhz-tenant/private-devfile/private-quarkus-devfile-sample-ur4m@sha256:c67069a9840cd8327b883b613e4ea29cf9a6971ba672540bf0648b36b7f319a0
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
